### ISSUE TITLE
Search requests should probably be put in double quotes

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/qit.cloud#250]
## 👣 Steps to reproduce
Search "Design Systems" you get more than a thousand results because "Design" and "Systems" are common words, but they have a special meaning together. If you quote the phrase then you only get 29 results, but they are much better results.

## 🔬 Expected behavior
Fewer results, better results.

## 🌳 Environments
Any/All

**Comment by Aditya-Kolla** [comment]
Can I try this?

**Comment by THEjoezack** [comment]
@Aditya-Kolla Sure, that would be great!

**Comment by davefollett** [comment]
I think this one is done, right?

**Comment by Aditya-Kolla** [comment]
Yeah, it's done. I forgot to add "this closes " in the PR description.
@THEjoezack please close this issue.

**Comment by davefollett** [comment]
Thanks for the contribution :)
