### ISSUE TITLE
Build broken because of event-stream debacle!

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/qit.cloud#253]
## 👣 Steps to reproduce
npm install throws an error about flatmap being unavailable, that's because the version of event-stream had been corrupted by evil and removed from npm.

## 🔬 Expected behavior
You should be able to build the website!

An easy fix is to update "start-server-and-test" - that will peg the event-stream version at the last good one.

## 🌳 Environments
Everywhere

**Comment by davefollett** [comment]
I think this one is done, right?

**Comment by davefollett** [comment]
@THEjoezack  fixed this a while back.
