### ISSUE TITLE
All Contributors:  Add Contributors List

### ISSUE THREAD

**Issue by davefollett** [codingblocks/qit.cloud#285]
## ✨ New feature description
This issue is just a place to add comments for adding contributors using the All Contributors bot.

General usage:

`@all-contributors please add <username> for <contributions>`

## 📑 Contributors To-Do List
- [x] Aaron Clawson (MadVikingGod)
- [x] Adam Lantz (AdamLantz)
- [x] Aditya Kolla (aditya-kolla)
- [x] Arlene Andrews (arleneandrews)
- [x] Ben Steward (tehpsalmist)
- [x] Brandon Lyons (lyonsbp)
- [x] Dave Follett (davefollett)
- [x] Joe Zack (THEjoezack)
- [x] Mikkel Madsen (Madsn)
- [x] Nicolas Marcora (nmarcora)
- [x] Paul Mcilreavy (pmcilreavy)
- [x] Sung Kim (dance2die)
- [x] Vladimir Kunarac (vlado92)

## ➕ Additional context
* [All Contributors Usage](https://all-contributors.js.org/docs/en/bot/usage)
* [All Contributors Contribution Types](https://all-contributors.js.org/docs/en/emoji-key)

**Comment by davefollett** [comment]
@all-contributors please add @THEjoezack  for code, design, infra, and doc

**Comment by vlado92** [comment]
@allcontributors[bot] please add @vlado92 for infra

**Comment by davefollett** [comment]
@all-contributors please add @davefollett k for code, infra, and doc
@all-contributors please add @Aditya-Kolla for code

**Comment by davefollett** [comment]
@all-contributors please add @davefollett for code, infra, and doc

@all-contributors please add @Aditya-Kolla for code

**Comment by davefollett** [comment]
@all-contributors please add @davefollett for code, infra, and doc

**Comment by davefollett** [comment]
@all-contributors please add @Aditya-Kolla for code

**Comment by jakebolam** [comment]
@davefollett thanks for using us! (I keep getting tagged, I'll sort that 😂).

FYI multi-add coming soon! https://github.com/all-contributors/all-contributors-bot/issues/100

**Comment by davefollett** [comment]
@all-contributors please add @Aditya-Kolla for code

**Comment by davefollett** [comment]
@jakebolam sorry about that! I was trying to speed up the process of switching over to all-contributors.

**Comment by davefollett** [comment]
@all-contributors please add @Aditya-Kolla for code

**Comment by davefollett** [comment]
@all-contributors please add @davefollett for test

**Comment by davefollett** [comment]
@all-contributors please add @davefollett for test

**Comment by jakebolam** [comment]
no worries, @davefollett. No sweat. Glad to see everything coming along!

**Comment by THEjoezack** [comment]
Note, there are a couple markdown warnings to take a peek at while I'm in there.
```
Cannot resolve anchor #contributors
Cannot resolve anchor #design-THEjoezack
Cannot resolve anchor #infra-THEjoezack
Cannot resolve anchor #infra-vlado92
Cannot resolve anchor #infra-davefollett```

**Comment by davefollett** [comment]
I fixed the anchor issues with PR #307 

The all contributors badge expects its contributors section to be named contributors.  Ours got changed to contributors (auto generated).

**Comment by lyonsbp** [comment]
@allcontributors[bot] please add @lyonsbp for test

**Comment by tehpsalmist** [comment]
@all-contributors please add @tehpsalmist for code

**Comment by dance2die** [comment]
@all-contributors please add @dance2die for doc

**Comment by davefollett** [comment]
@allcontributors[bot]  please add @lyonsbp for test

**Comment by davefollett** [comment]
@allcontributors[bot] please add @tehpsalmist for code

**Comment by THEjoezack** [comment]
@allcontributors[bot] please add @MadVikingGod for code

**Comment by THEjoezack** [comment]
Lets see if multiple works :)
@allcontributors[bot] please add @AdamLantz for code
@allcontributors[bot] please add @Madsn for code, infra
@allcontributors[bot] please add @pmcilreavy for code

**Comment by THEjoezack** [comment]
doh!
@allcontributors[bot] please add @AdamLantz for code

**Comment by THEjoezack** [comment]
@allcontributors[bot] please add @Madsn for code, infra

**Comment by THEjoezack** [comment]
@allcontributors[bot] please add @pmcilreavy for code

**Comment by THEjoezack** [comment]
@allcontributors[bot] add @MinimumViablePerson for code, test

**Comment by THEjoezack** [comment]
yo @allcontributors[bot] can you please add @Ju66ernaut for code

**Comment by THEjoezack** [comment]
@allcontributors[bot] can you please add @temaEmelyan for code

**Comment by THEjoezack** [comment]
@allcontributors[bot] please...uh...refresh ?

**Comment by THEjoezack** [comment]
@all-contributors please add @codingblocks/qit-working-title for code, doc and infra

**Comment by davefollett** [comment]
Looks like we are all caught up.  For now on, I think a comment on each contributors PR would be a good place to add them.
